name 'chocolatey_packages'
maintainer 'Luke Watson'
maintainer_email 'luwatson90@gmail.com'
license 'all_rights'
version '0.0.1'
issues_url 'https://github.com/watsonlu/chocolatey_packages/issues'
source_url 'https://github.com/watsonlu/chocolatey_packages'
